on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        npm ci

    - name: Lint code
      run: |
        npm run lint

    - name: Run tests
      run: |
        npm test

    - name: Build with Vite
      run: |
        npx vite build

    - name: Validate build
      run: |
        echo "Validating build output..."
        # Here you can add commands to verify the build (e.g., check for expected files)

    - name: Cleanup
      run: |
        echo "Cleaning up build artifacts..."
        # Add cleanup commands if necessary
